modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="ninjaxx_mod"
version="0.1"
displayName="Ninjaxx Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Infinitumcraft, SkyFox, Solaris"
description='''
Ninjaxx Mod (Toujours Dans Le Making)
'''

[[dependencies.ninjaxx_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.ninjaxx_mod]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0]"
    ordering="NONE"
    side="BOTH"



